name: Build Box64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Build in Arch Linux Container
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace archlinux:latest bash -c "
        pacman -Syu --noconfirm &&
        pacman -S --noconfirm base-devel glibc git cmake make &&
        git clone https://github.com/MarkZingrim/box64 &&
        cd box64 &&
        patch -p1 < ../patches/box64-setdirs.patch &&
        mkdir build &&
        cd build &&
        cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DARM_DYNAREC=ON -DBAD_SIGNAL=ON &&
        make
        "

    - name: Upload Box64 Binary
      uses: actions/upload-artifact@v3
      with:
        name: box64-binary
        path: box64/build/box64

